-- Diani Sea Adventures - Supabase/PostgreSQL schema
-- Run this once in the Supabase Dashboard -> SQL Editor.
--
-- The Flask server uses SUPABASE_SECRET_KEY, so the tables are not exposed
-- directly to visitors. Row Level Security is enabled as a defense-in-depth
-- measure; the server-side secret key bypasses RLS.

create table if not exists public.safaris (
    id bigint generated by default as identity primary key,
    slug text unique not null,
    accent text default 'lagoon',
    emoji text default '',
    name jsonb not null,
    tagline jsonb default '{}'::jsonb,
    teaser jsonb default '{}'::jsonb,
    duration jsonb default '{}'::jsonb,
    group_size jsonb default '{}'::jsonb,
    price jsonb default '{}'::jsonb,
    difficulty jsonb default '{}'::jsonb,
    departs jsonb default '{}'::jsonb,
    best_time jsonb default '{}'::jsonb,
    overview jsonb default '{}'::jsonb,
    highlights jsonb default '{}'::jsonb,
    included jsonb default '{}'::jsonb,
    excluded jsonb default '{}'::jsonb,
    bring jsonb default '{}'::jsonb,
    itinerary jsonb default '{}'::jsonb,
    display_order integer default 0
);

create table if not exists public.gallery_images (
    id bigint generated by default as identity primary key,
    safari_id bigint not null references public.safaris(id) on delete cascade,
    filename text not null,
    uploaded_at timestamptz not null default now()
);

create table if not exists public.inquiries (
    id bigint generated by default as identity primary key,
    name text not null,
    email text not null,
    phone text default '',
    message text not null,
    safari_id bigint references public.safaris(id) on delete set null,
    received_at timestamptz not null default now()
);

create index if not exists gallery_images_safari_id_idx
    on public.gallery_images(safari_id);

create index if not exists inquiries_safari_id_idx
    on public.inquiries(safari_id);

create index if not exists inquiries_received_at_idx
    on public.inquiries(received_at desc);

alter table public.safaris enable row level security;
alter table public.gallery_images enable row level security;
alter table public.inquiries enable row level security;

-- This application intentionally keeps all Data API access on the Flask
-- backend. The server uses the Supabase secret key, so no anon/authenticated
-- policies are needed for the application's normal operation.
grant all on table public.safaris to service_role;
grant all on table public.gallery_images to service_role;
grant all on table public.inquiries to service_role;
grant usage, select on all sequences in schema public to service_role;


-- Public media bucket for website images. Only the backend uses the secret key
-- for uploads/deletes; visitors only need public read access.
insert into storage.buckets (id, name, public)
values ('media', 'media', true)
on conflict (id) do update set public = true;

create policy "Public can read media"
on storage.objects for select
using (bucket_id = 'media');

create policy "Service role can manage media"
on storage.objects for all to service_role
using (bucket_id = 'media')
with check (bucket_id = 'media');
